// <auto-generated />
namespace MenuDelDia.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class menu_description_not_required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(menu_description_not_required));
        
        string IMigrationMetadata.Id
        {
            get { return "201505100601357_menu_description_not_required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
