//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuDelDia.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MenuDelDia.API.Resources.MessagesResources", typeof(MessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos ingresados no son válidos..
        /// </summary>
        public static string CompanyInvalidData {
            get {
                return ResourceManager.GetString("CompanyInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El restaurant indicado no se encuentra registrado en el sistema..
        /// </summary>
        public static string CompanyNotExist {
            get {
                return ResourceManager.GetString("CompanyNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viernes.
        /// </summary>
        public static string DayOfWeekFriday {
            get {
                return ResourceManager.GetString("DayOfWeekFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunes.
        /// </summary>
        public static string DayOfWeekMonday {
            get {
                return ResourceManager.GetString("DayOfWeekMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sábado.
        /// </summary>
        public static string DayOfWeekSaturday {
            get {
                return ResourceManager.GetString("DayOfWeekSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domingo.
        /// </summary>
        public static string DayOfWeekSunday {
            get {
                return ResourceManager.GetString("DayOfWeekSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jueves.
        /// </summary>
        public static string DayOfWeekThursday {
            get {
                return ResourceManager.GetString("DayOfWeekThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martes.
        /// </summary>
        public static string DayOfWeekTuesday {
            get {
                return ResourceManager.GetString("DayOfWeekTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miércoles.
        /// </summary>
        public static string DayOfWeekWednesday {
            get {
                return ResourceManager.GetString("DayOfWeekWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En este momento no hemos podido procesar su solicitud. Por favor inténtelo nuevamente en unos instantes..
        /// </summary>
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos se han almacenado con éxito..
        /// </summary>
        public static string GeneralSaveSucces {
            get {
                return ResourceManager.GetString("GeneralSaveSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos ingresados no son válidos..
        /// </summary>
        public static string LocationInvalidData {
            get {
                return ResourceManager.GetString("LocationInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El local ingresado no se encuentra registrado en el sistema..
        /// </summary>
        public static string LocationNotExist {
            get {
                return ResourceManager.GetString("LocationNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario logueado no se encuentra registrado en el sistema..
        /// </summary>
        public static string LoggedUserNotValid {
            get {
                return ResourceManager.GetString("LoggedUserNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos ingresados no son válidos..
        /// </summary>
        public static string MenuInvalidData {
            get {
                return ResourceManager.GetString("MenuInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo ingresado ya se encuentra registrado. Ingrese otro correo..
        /// </summary>
        public static string RegisterUserEmailExist {
            get {
                return ResourceManager.GetString("RegisterUserEmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hemos podido registrar su usuario en el sistema. Por favor inténtelo nuevamente en unos instantes..
        /// </summary>
        public static string RegisterUserFail {
            get {
                return ResourceManager.GetString("RegisterUserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos ingresados no son válidos..
        /// </summary>
        public static string RegisterUserInvalidData {
            get {
                return ResourceManager.GetString("RegisterUserInvalidData", resourceCulture);
            }
        }
    }
}
